### ISSUE TITLE
Extremely slow inference speed when using vLLM (≈400s per sample)

### ISSUE THREAD

**Issue by YiboZhao624** [ren258/ARENA#5]
Hello, thank you for releasing this model checkpoint!

After downloading it from Hugging Face and running inference with `vLLM`, I noticed that the inference speed is extremely slow — around 400 seconds per sample.

Below are the commands and code I used for reproduction.

vLLM launch command:

```
export NCCL_P2P_DISABLE=1 
export CUDA_VISIBLE_DEVICES=0
python3 -m vllm.entrypoints.openai.api_server\
    --model ARENA-7b\
    --port 8004\
    --dtype bfloat16\
    --gpu-memory-utilization 0.9\
    --max-model-len 32768\
    --tensor-parallel-size 1
```

Inference code:

```
import requests
import os
import openai
from openai import OpenAI
from typing import Union
from dataclasses import dataclass

@dataclass
class LLMConfig:
    # compatible with vLLM and GPT, for GPT, the url is not used as we deployed the openai package.
    model_name: str = "ARENA-7b"
    url: str = "http://localhost:8004"

class vLLM(LLM):
    def __init__(self, config: LLMConfig):
        super().__init__(config)
        self.base_url = config.url
        self.model_name = config.model_name

    def generate(self, user_input:Union[dict, str], sys_prompt:Union[dict, str] = None) -> str:
        url = f"{self.base_url}/v1/chat/completions"
        headers = {"Content-Type": "application/json"}
        messages = []
        if isinstance(sys_prompt, dict):
            messages.append(sys_prompt)
        elif isinstance(sys_prompt, str):
            messages.append({"role": "system", "content": sys_prompt})
        if isinstance(user_input, dict):
            messages.append(user_input)
        elif isinstance(user_input, str):
            messages.append({"role": "user", "content": user_input})
        else:
            raise ValueError(f"Invalid user input type: {type(user_input)}")
        data = {
            "model": self.model_name,
            "messages": messages,
        }
        try:
            response = requests.post(url, headers=headers, json=data)
            response.raise_for_status()
            response_json = response.json()
            content = response_json["choices"][0]["message"]["content"]
            return content.strip()

        except requests.exceptions.RequestException as e:
            print(f"Error: Network request failed: {e}")
            return "ERROR: THE MODEL CANNOT PROCESS THE REQUEST."
        except (KeyError, IndexError) as e:
            print(f"Error: Could not parse the response JSON: {e}")
            print(f"Received response: {response.text}")
            return "ERROR: THE MODEL CANNOT PROCESS THE REQUEST."

if __name__ == "__main__":
    config = LLMConfig(
        url="http://localhost:8004",
        model_name="ARENA-7b",
    )
    arena = vLLM(config)
    print(arena.generate("What is the capital of France?"))
```
It takes a long time to reply to this simple question, around 6-7 minutes with a single A800 GPU. In contrast, the original Qwen2.5-7B-Instruct only takes less than 1 second to reply. This suggests the issue might be related to this checkpoint’s configuration or weight format compatibility with vLLM.

Would appreciate any insights or fixes you could provide. Thanks again for your work!

Environment details:

CUDA:12.4
vLLM: 0.8.5
python: 3.12.2
Operating System: Ubuntu 22.04

**Comment by YiboZhao624** [comment]
It's also worth noting that the response to the "What is the capital of France?" only includes some repetition. When the prompt changed to the training format and only included a short paragraph of evidence, it could return the answer immediately as expected, like the following prompt:

```
<|im_start|>system\nA conversation between User and Assistant. The user asks a question and give some references. The assistant should answer the question based on the references. \nUser\'s input will always contain:\n\n<question>\n[The question to answer]\n</question>\n\n<references>\n[References starting with numbers]\n</references>\n\nAssistant\'s response must contain EXACTLY three sections if the references are relevant and useful to the question, otherwise, the assistant should output "The provided evidence is not enough to answer the question." only.\n\n<relevance>\n[List ONLY reference numbers that provide useful information in square brackets, e.g. [1,5]]\n</relevance>\n\n<analysis>\n[Combine information from relevant references to build the answer. Explicitly mention which references support each claim]\n</analysis>\n\n<answer>\n[Answer with ONLY a short phrase or single word. No explanations]\n</answer><|im_end|>\n<|im_start|>user\n<question>\nHow big is the ANTISCAM dataset? \n</question>\n\n<references>\n1.To enrich available non-collaborative task datasets, we created a corpus of human-human anti-scam dialogs in order to learn human elicitation strategies. We chose a popular Amazon customer service scam scenario to collect dialogs between users and attackers who aim to collect users information. We posted a role-playing task on the Amazon Mechanical Turk platform and collected a typing conversation dataset named AntiScam. We collected 220 human-human dialogs. The average conversation length is 12.45 turns and the average utterance length is 11.13 words. Only 172 out of 220 users successfully identified their partner as an attacker, suggesting that the attackers are well trained and not too easily identifiable. We recruited two expert annotators who have linguistic training to annotate 3,044 sentences in 100 dialogs, achieving a 0.874 averaged weighted kappa value.\n</references><|im_end|>\n<|im_start|>assistant\n
```

When the prompt is extended longer, like the following input:

```
<|im_start|>system\nA conversation between User and Assistant. The user asks a question and give some references. The assistant should answer the question based on the references. \nUser\'s input will always contain:\n\n<question>\n[The question to answer]\n</question>\n\n<references>\n[References starting with numbers]\n</references>\n\nAssistant\'s response must contain EXACTLY three sections if the references are relevant and useful to the question, otherwise, the assistant should output "The provided evidence is not enough to answer the question." only.\n\n<relevance>\n[List ONLY reference numbers that provide useful information in square brackets, e.g. [1,5]]\n</relevance>\n\n<analysis>\n[Combine information from relevant references to build the answer. Explicitly mention which references support each claim]\n</analysis>\n\n<answer>\n[Answer with ONLY a short phrase or single word. No explanations]\n</answer><|im_end|
>\n<|im_start|>user\n<question>\nHow is intent annotated?\n</question>\n\n<references>\n1.Datasets ::: PersuasionForGood Dataset\n\n2.The PersuasionForGood dataset BIBREF1 was collected from typing conversations on Amazon Mechanical Turk platform. Two workers were randomly paired, one was assigned the role of persuader, the other was persuadee. The goal of the persuader was to persuade the persuadee to donate a portion of task earning to a specific charity. The dataset consists of 1,017 dialogs, where 300 dialogs are annotated with dialog acts. The average conversation length is 10.43, the vocabulary size is 8,141. Since the original PersuasionForGood dataset is annotated with dialog acts, we select the on-task dialog acts as on-task intents shown in Table TABREF2, and categorize the other dialog acts into our pre-defined off-task intents.\n\n3.FLOAT SELECTED: Table 1: Hierarchical intent annotation scheme on both ANTISCAM dataset and PERSUASIONFORGOOD dataset. The On-task intents are task-specific while the Off-task intents are general for different non-collaborative tasks.\n\n4.To decouple syntactic and semantic information in utterances and provide detailed supervision, we design a hierarchical intent annotation scheme for non-collaborative tasks. We first separate on-task and off-task intents. As on-task intents are key actions that can vary among different tasks, we need to specifically define on-task intents for each task. On the other hand, since off-task content is too general to design task-specific intents, we choose common dialog acts as the categories. The advantage of this hierarchical annotation scheme is apparent when starting a new non-collaborative task: we only need to focus on designing the on-task categories and semantic slots which are the same as traditional task-oriented dialog systems. Consequently, we don\'t have to worry about the off-task annotation design since the off-task category is universal.\n\n5.To enrich available non-collaborative task datasets, we created a corpus of human-human anti-scam dialogs in order to learn human elicitation strategies. We chose a popular Amazon customer service scam scenario to collect dialogs between users and attackers who aim to collect users information. We posted a role-playing task on the Amazon Mechanical Turk platform and collected a typing conversation dataset named AntiScam. We collected 220 human-human dialogs. The average conversation length is 12.45 turns and the average utterance length is 11.13 words. Only 172 out of 220 users successfully identified their partner as an attacker, suggesting that the attackers are well trained and not too easily identifiable. We recruited two expert annotators who have linguistic training to annotate 3,044 sentences in 100 dialogs, achieving a 0.874 averaged weighted kappa value.\n\n6.To enrich publicly available non-collaborative task datasets, we collect a new dataset AntiScam, where users defend themselves against attackers trying to collect personal information. As non-collaborative tasks are still relatively new to the study of dialog systems, here are insufficiently many meaningful datasets for evaluation and we hope this provides a valuable example. We evaluate MISSA on the newly collected AntiScam dataset and an existing PersuasionForGood dataset. Both automatic and human valuations suggest that MISSA outperforms multiple competitive baselines.\n\n7.In the intent annotation scheme shown in Table TABREF2, we list the designed intent annotation scheme for the newly collected AntiScam dataset and the PersuasionForGood dataset. We first define on-task intents for the datasets, which are key actions in the task. Since our AntiScam focuses on understanding and reacting towards elicitations, we define elicitation, providing_information and refusal as on-task intents. In the PersuasionForGood dataset, we define nine on-task intents in Table TABREF2 based on the original PersuasionForGood dialog act annotation scheme. All these intents are related to donation actions, which are salient on-task intents in the persuasion task. The off-task intents are the same for both tasks, including six general intents and six additional social intents. General intents are more closely related to the syntactic meaning of the sentence (open_question, yes_no_question, positive_answer, negative_answer, responsive_statement, and nonresponsive_statement) while social intents are common social actions (greeting, closing, apology, thanking,respond_to_thank, and hold).\n\n8.For specific tasks, we also design a semantic slot annotation scheme for annotating sentences based on their semantic content. We identify 13 main semantic slots in the anti-scam task, for example, credit card numbers. We present a detailed semantic slot annotation in Table TABREF3. Following BIBREF1, we segment each conversation turn into single sentences and then annotate each sentence rather than turns.\n\n9.To tackle the issue of incoherent system responses to off-task content, previous studies have built hybrid systems to interleave off-task and on-task content. BIBREF4 used a rule-based dialog manager for on-task content and a neural model for off-task content, and trained a reinforcement learning model to select between these two models based on the dialog context. However, such a method is difficult to train and struggles to generalize beyond the movie promotion task they considered. To tackle these problems, we propose a hierarchical intent annotation scheme that separates on-task and off-task information in order to provide detailed supervision. For on-task information, we directly use task-related intents for representation. Off-task information, on the other hand, is too general to categorize into specific intents, so we choose dialog acts that convey syntax information. These acts, such as “open question" are general to all tasks.\n</references><|im_end|>\n<|im_start|>assistant\n
```

It takes 244.15s to response. This issue might be related to the training data distribution — very long input sequences could exceed the model’s effective context capability, or there may be other underlying factors.

I really appreciate your time and help in investigating this.

**Comment by ren258** [comment]
Hi, thanks again for using our model and for continuously providing feedback!

We recommend running inference via the provided script `scripts/run_inference.sh`, which internally calls `src/vllm_inference.py`. You only need to organize the input data into the expected format. We ran the two examples you shared, and the total inference time was less than **1 second** on our side:

```
{"prompt": [{"role": "user", "content": "A conversation between User and Assistant. The user asks a question and give some references. The assistant should answer the question based on the references. \nUser's input will always contain:\n\n<question>\n[The question to answer]\n</question>\n\n<references>\n[References starting with numbers]\n</references>\n\nAssistant's response must contain EXACTLY three sections if the references are relevant and useful to the question, otherwise, the assistant should output \"The provided evidence is not enough to answer the question.\" only.\n\n<relevance>\n[List ONLY reference numbers that provide useful information in square brackets, e.g. [1,5]]\n</relevance>\n\n<analysis>\n[Combine information from relevant references to build the answer. Explicitly mention which references support each claim]\n</analysis>\n\n<answer>\n[Answer with ONLY a short phrase or single word. No explanations]\n</answer>\n\n**User**:\n\n<question>\nHow big is the ANTISCAM dataset? \n</question>\n\n<references>\n1.To enrich available non-collaborative task datasets, we created a corpus of human-human anti-scam dialogs in order to learn human elicitation strategies. We chose a popular Amazon customer service scam scenario to collect dialogs between users and attackers who aim to collect users information. We posted a role-playing task on the Amazon Mechanical Turk platform and collected a typing conversation dataset named AntiScam. We collected 220 human-human dialogs. The average conversation length is 12.45 turns and the average utterance length is 11.13 words. Only 172 out of 220 users successfully identified their partner as an attacker, suggesting that the attackers are well trained and not too easily identifiable. We recruited two expert annotators who have linguistic training to annotate 3,044 sentences in 100 dialogs, achieving a 0.874 averaged weighted kappa value.\n</references>\n"}], "model_response": "<relevance>\n[1]\n</relevance>\n\n<analysis>\nThe dataset consists of 220 human-human dialogs. Each dialog has an average conversation length of 12.45 turns.\n</analysis>\n\n<answer>\n220 dialogs\n</answer>", "supporting_ids": [], "name": "", "answers": [""]}
{"prompt": [{"role": "user", "content": "A conversation between User and Assistant. The user asks a question and give some references. The assistant should answer the question based on the references. \nUser's input will always contain:\n\n<question>\n[The question to answer]\n</question>\n\n<references>\n[References starting with numbers]\n</references>\n\nAssistant's response must contain EXACTLY three sections if the references are relevant and useful to the question, otherwise, the assistant should output \"The provided evidence is not enough to answer the question.\" only.\n\n<relevance>\n[List ONLY reference numbers that provide useful information in square brackets, e.g. [1,5]]\n</relevance>\n\n<analysis>\n[Combine information from relevant references to build the answer. Explicitly mention which references support each claim]\n</analysis>\n\n<answer>\n[Answer with ONLY a short phrase or single word. No explanations]\n</answer>\n\n**User**:\n\n<question>\nHow is intent annotated?\n</question>\n\n<references>\n1.Datasets ::: PersuasionForGood Dataset\n\n2.The PersuasionForGood dataset BIBREF1 was collected from typing conversations on Amazon Mechanical Turk platform. Two workers were randomly paired, one was assigned the role of persuader, the other was persuadee. The goal of the persuader was to persuade the persuadee to donate a portion of task earning to a specific charity. The dataset consists of 1,017 dialogs, where 300 dialogs are annotated with dialog acts. The average conversation length is 10.43, the vocabulary size is 8,141. Since the original PersuasionForGood dataset is annotated with dialog acts, we select the on-task dialog acts as on-task intents shown in Table TABREF2, and categorize the other dialog acts into our pre-defined off-task intents.\n\n3.FLOAT SELECTED: Table 1: Hierarchical intent annotation scheme on both ANTISCAM dataset and PERSUASIONFORGOOD dataset. The On-task intents are task-specific while the Off-task intents are general for different non-collaborative tasks.\n\n4.To decouple syntactic and semantic information in utterances and provide detailed supervision, we design a hierarchical intent annotation scheme for non-collaborative tasks. We first separate on-task and off-task intents. As on-task intents are key actions that can vary among different tasks, we need to specifically define on-task intents for each task. On the other hand, since off-task content is too general to design task-specific intents, we choose common dialog acts as the categories. The advantage of this hierarchical annotation scheme is apparent when starting a new non-collaborative task: we only need to focus on designing the on-task categories and semantic slots which are the same as traditional task-oriented dialog systems. Consequently, we don't have to worry about the off-task annotation design since the off-task category is universal.\n\n5.To enrich available non-collaborative task datasets, we created a corpus of human-human anti-scam dialogs in order to learn human elicitation strategies. We chose a popular Amazon customer service scam scenario to collect dialogs between users and attackers who aim to collect users information. We posted a role-playing task on the Amazon Mechanical Turk platform and collected a typing conversation dataset named AntiScam. We collected 220 human-human dialogs. The average conversation length is 12.45 turns and the average utterance length is 11.13 words. Only 172 out of 220 users successfully identified their partner as an attacker, suggesting that the attackers are well trained and not too easily identifiable. We recruited two expert annotators who have linguistic training to annotate 3,044 sentences in 100 dialogs, achieving a 0.874 averaged weighted kappa value.\n\n6.To enrich publicly available non-collaborative task datasets, we collect a new dataset AntiScam, where users defend themselves against attackers trying to collect personal information. As non-collaborative tasks are still relatively new to the study of dialog systems, here are insufficiently many meaningful datasets for evaluation and we hope this provides a valuable example. We evaluate MISSA on the newly collected AntiScam dataset and an existing PersuasionForGood dataset. Both automatic and human valuations suggest that MISSA outperforms multiple competitive baselines.\n\n7.In the intent annotation scheme shown in Table TABREF2, we list the designed intent annotation scheme for the newly collected AntiScam dataset and the PersuasionForGood dataset. We first define on-task intents for the datasets, which are key actions in the task. Since our AntiScam focuses on understanding and reacting towards elicitations, we define elicitation, providing_information and refusal as on-task intents. In the PersuasionForGood dataset, we define nine on-task intents in Table TABREF2 based on the original PersuasionForGood dialog act annotation scheme. All these intents are related to donation actions, which are salient on-task intents in the persuasion task. The off-task intents are the same for both tasks, including six general intents and six additional social intents. General intents are more closely related to the syntactic meaning of the sentence (open_question, yes_no_question, positive_answer, negative_answer, responsive_statement, and nonresponsive_statement) while social intents are common social actions (greeting, closing, apology, thanking,respond_to_thank, and hold).\n\n8.For specific tasks, we also design a semantic slot annotation scheme for annotating sentences based on their semantic content. We identify 13 main semantic slots in the anti-scam task, for example, credit card numbers. We present a detailed semantic slot annotation in Table TABREF3. Following BIBREF1, we segment each conversation turn into single sentences and then annotate each sentence rather than turns.\n\n9.To tackle the issue of incoherent system responses to off-task content, previous studies have built hybrid systems to interleave off-task and on-task content. BIBREF4 used a rule-based dialog manager for on-task content and a neural model for off-task content, and trained a reinforcement learning model to select between these two models based on the dialog context. However, such a method is difficult to train and struggles to generalize beyond the movie promotion task they considered. To tackle these problems, we propose a hierarchical intent annotation scheme that separates on-task and off-task information in order to provide detailed supervision. For on-task information, we directly use task-related intents for representation. Off-task information, on the other hand, is too general to categorize into specific intents, so we choose dialog acts that convey syntax information. These acts, such as “open question\" are general to all tasks.\n</references>\n"}], "model_response": "<relevance>\n[4,7]\n</relevance>\n\n<analysis>\nReference 4 describes the hierarchical intent annotation scheme, which separates on-task and off-task intents. Reference 7 provides the specific defined on-task intents for the PersuasionForGood dataset, including nine donation-related intents, and off-task intents, which are the same for both tasks. \n\nBoth references support the statement that intent is annotated by separating on-task and off-task intents and defining specific intents for both categories.\n</analysis>\n\n<answer>\nBy separating on-task and off-task intents and defining specific intents for both categories\n</answer>", "supporting_ids": [], "name": "", "answers": [""]}
```

In our tests, running inference on the 500-sample HotpotQA test set with a single A100-80G GPU takes about **1 minute** in total.

As for other tasks, as stated in our paper, our model has been further trained with 25,000 structured data samples specifically for RAG tasks. Therefore, compared with the original Qwen2.5-7B-Instruct, the behavior may differ on other tasks and prompts. We strongly recommend using our released model **only for RAG-related tasks**.

For reference, our environment was: **CUDA 12.4, vLLM 0.7.2, Python 3.11.12, Ubuntu 22.04**. This setup is slightly different from yours, but we believe it is not a key factor affecting inference efficiency.

We hope this helps resolve your issue!

**Comment by YiboZhao624** [comment]
Thank you very much for your response. Using the scripts provided in the original code has significantly improved the inference speed. However, I still haven’t identified the reason why my initial implementation caused such unexpected behavior. It would be greatly appreciated if you could help look into what might have caused this.

I’ll keep this issue open for now to share any further experimental results once available. Many thanks again for your time and for the multiple helpful replies. I really appreciate your support.

**Comment by YiboZhao624** [comment]
I used the checkpoint ARENA-7B (based on Qwen) that you released on Hugging Face to perform inference and evaluation on the 500 HotpotQA samples you provided. Unexpectedly, the inference results were inconsistent with those reported in the paper. I suspect there might be an issue with my model or some part of the pipeline. My code is as follows:

```
export CUDA_VISIBLE_DEVICES=3

python ../src/vllm_inference.py --name "hotpotqa" --testdata-name "test" --saved-name "hotpotqa-500" --model-path "./ARENA-7b"
```

for evaluation:

```
python ../src/evaluate.py --name "hotpotqa" --result-name "hotpotqa-500"
```

It prints:

```
Input file: ../results/vllm_inference_results/hotpotqa/hotpotqa-500.jsonl
Output file: ../results/eval_rulebase/hotpotqa/hotpotqa-500.json
eval_jsonl: ../results/vllm_inference_results/hotpotqa/hotpotqa-500.jsonl -> ../results/eval_rulebase/hotpotqa/hotpotqa-500.json
total: 500, em_score: 0.01, f1_score: 0.036466845300806405, format_score: 0.0, accuracy_score: 0.01, relevance_score: 0.006, bonus_score: 0.0
```

For example, the response to the question 'What city is the army division that conducted Operation Blue Hearts in the Korean War based out of?'(which is the first in the test set) is: 

```
"[References]\n[1,2]\n\n<references>\n[3,4]\n</references>\n\n**Relevance and References**\n\n**Operation Blue Star**\n- **Reference**: The 1984 operation to capture the Golden Temple in Amritsar, which was part of the military operation to establish control over the Golden Temple.\n\n**References**\n- **Operation Blue**: Rockefeller, R. M. L. (1996)\n\n- **Operation Blue Star**: References to the Operation Blue Star in the Indo-Pakistani war of 1971. The operation was conducted by the Indian Army (Indian Army had no direct involvement in Operation Blue Star).\n\n- **References to Operation Blue Star**: Operation Blue Star (1984) was a significant event in the Indian Army's history, leading to the successful capture and subsequent control of the Golden Temple in Amritsar.\n\n**References:**\n1. **Operation Blue Star**: Operation Blue Star (1984) was a significant event in the Indian Army's history, leading to the successful capture and subsequent control of the Golden Temple in Amritsar.\n\n**Analysis:** The 1984 Operation Blue Star was considered a pivotal event in Indian military history.\n\n**Historical Context:**\n- Operation Blue was a code name for the operation that took place on 6–8 June 1984, right before the Indian army concentrated on capturing the Golden Temple in Amritsar.\n\n**Operation Blue Star:**\n- **References to Operation Blue Star**: Operation Blue Star was a significant event in the history of the Indian army's response to the Golden Temple and was conducted in 1984. The operation was aimed at liberating Khalungian, which was part of Operation Blue Star. This operation was a code name for the operation that successfully ended the Golden Temple assault.\n\n**Analysis: Operation Blue Star involved the 1984 Indian army operation, which is a significant event in the army's military history.**\n**Relevance of Operation Blue Star**:\n- **References to Operation Blue Star**: The liberation of the Golden Temple in 1984 was a significant event in the Operation Blue Star, which was a code name for the forced entry into the Golden Temple.\n\n**References to the 1984 Operation Blue Star**: Operation Blue Star was a significant event in the Indian army's history, leading to the liberation of Punjab region which led to the successful capture and control of the Golden Temple.\n\n**Analysis:** The 1984 Operation Blue Star involved the 1984 Indian army operation, which involved the successful capture and control of the Golden Temple.\n\n**References**\n[3,4]\n\n**Conclusion:** Operation Blue Star was a pivotal event in the history of the Indian army's military campaign, which led to the liberation of Punjab region which led to the successful capture and control of the Golden Temple.\n</references>\n\n**Analysis** of the references provided supports the historic context of Operation Blue Star and Operation Blue. The references indicate Operation Blue Star was a significant event led by the Indian army in 1984, which demonstrated how the Indian army successfully carried out the golden temple liberation in 1984.\n\n**Supporting References**\n- **Operation Blue Star**: Operation Blue was a pivotal event in 1984, in which the Indian Army conducted the successful capture and control of the Golden Temple.\n\n**References:**\n[1,2]\n\n**Operation Blue Star**: References to Operation Blue Star were significant in the war, leading to the liberation of the Golden Temple. This operation was a collective code name for the actions carried out by the Indian Army in 1984, which were part of Operation Blue Star.\n\n**References**\n- Operation Blue Star: Operation blue star was a significant event in 1984, in which the Indian army liberated and controlled the Golden Temple in Amritsar. The references to Operation Blue Star were significant in the Indian Army's military operations.\n\n**References:**\n[Operation Blue Star]\n\n**Analysis:** The 1984 Operation Blue Star was a significant event in the history of the Indian army, marking the liberation of the Golden Temple and the successful operation of the Indian army in Amritsar. As per [3,4], Operation Blue Star was a significant event in 1984, in which the Indian army liberated the Golden Temple in Amritsar.\n\n**References to the capture of the Golden Temple in Operation Blue Star**: Operation Blue Star was a pivotal event in the history of the Indian army, leading to the liberation of the Golden Temple. This operation was a significant event in the Indian Army's military operations in 1984.\n\n**References**\n[Operation Blue Star]\n\n**Conclusion:** Operation Blue Star involved the Indian army's successful capture and the Golden Temple Liberation.\n\n**References:**\n[Operation Blue Star and Golden Temple Liberation, 1984]\n\n**References:**\n- Operation Blue Star: Operation Blue Star\n\n**Analysis:** The "
```

which is cut by the max token limit.

I did not modify your Python code, nor did I change any parameters other than the input and output file paths. I suspect the issue might be caused by a corrupted model file during download. I executed the command `find . -type f -name "*.safetensors" -print0 | sort -z | xargs -0 sha256sum > model_hashes.sha256` in the folder ARENA-7b. Here are the hash results of my model files:

```
0ae6334d2d91d24b8af477f49ac288e6f7f35ec388937fc74fc5c21b8b601d17  ./model-00001-of-00004.safetensors
0301fb98320d49da2e512a70e459306321172092130bff664d383bee644c9233  ./model-00002-of-00004.safetensors
10798eb80fd6f697c8ebd5658ac3671ad409be7cb543f4c20accd83c5dd045f0  ./model-00003-of-00004.safetensors
9c929cfefca9dcdc47c2a469d62b8626d0b97e479b61c9512d753f24b1a7bda5  ./model-00004-of-00004.safetensors
```

Many thanks again!

**Comment by ren258** [comment]
Hi—thanks for the detailed report; to confirm, your HotpotQA test-set processing looks correct.

We re-downloaded the four shards from Hugging Face and compared them with our original uploads; the canonical SHA256 checksums are:

```
0ae6334d2d91d24b8af477f49ac288e6f7f35ec388937fc74fc5c21b8b601d17  ./model-00001-of-00004.safetensors
eeec57399f5e40848603ffa89bbc7fb4f93545ac59f57fb105e4bac4b573a278  ./model-00002-of-00004.safetensors
10798eb80fd6f697c8ebd5658ac3671ad409be7cb543f4c20accd83c5dd045f0  ./model-00003-of-00004.safetensors
9c929cfefca9dcdc47c2a469d62b8626d0b97e479b61c9512d753f24b1a7bda5  ./model-00004-of-00004.safetensors
```

Your values for 1/3/4 match these exactly, only **part 2** differs on your side. When convenient, please try re-downloading just `model-00002-of-00004.safetensors`, hopefully this also resolves the inference anomaly you observed. If anything still looks off we’re happy to investigate further.

**Comment by YiboZhao624** [comment]
Thank you so much! After re-downloading part 2, the model now performs perfectly, and the results **match the reported values exactly**. I really appreciate your excellent work and all your help, thanks again!
